INSERT INTO USER_ACCOUNT (FULLNAME, USERNAME, PROFILE_URL)
VALUES 
  ('John Doe', 'jdoe', 'profile-1.jpg'),
  ('Alice Wonderland', 'awond', 'profile-2.jpg'),
  ('Sita Dennis', 'sitad', 'profile-3.jpg'),
  ('Sasha Mateo', 'matte', 'profile-4.jpg'),
  ('Anita Austi', 'anita', 'profile-5.jpg'),
  ('Lukas Souza', 'lsouza', 'profile-6.jpg'),
  ('Jose Alejandro', 'josea', 'profile-7.jpg'),
  ('Dwayne Jacob', 'jdwayne', 'profile-8.jpg'),
  ('Allison Saeng', 'saeng', 'profile-9.jpg'),
  ('Adrea Santos', 'santa', 'profile-10.jpg');

INSERT INTO TOPIC (TITLE, SLUG)
VALUES 
  ('People', 'people'),
  ('Nature', 'nature'),
  ('Travel', 'travel'),
  ('Animals', 'animals'),
  ('Fashion', 'fashion');

INSERT INTO PHOTO (FULL_URL, REGULAR_URL, CITY, COUNTRY, USER_ID, TOPIC_ID)
VALUES 
  ('Image-1-Full.jpeg', 'Image-1-Regular.jpeg', 'Montreal', 'Canada', 1, 1),
  ('people-1-full.jpg', 'people-1-regular.jpg', 'Toronto', 'Canada', 1, 1),
  ('people-2-full.jpg', 'people-2-regular.jpg', 'Vancouver', 'Canada', 2, 1),
  ('people-3-full.jpg', 'people-3-regular.jpg', 'Calgary', 'Canada', 3, 1),
  ('people-4-full.jpg', 'people-4-regular.jpg', 'Victoria', 'Canada', 4, 1),
  ('people-5-full.jpg', 'people-5-regular.jpg', 'Ottawa', 'Canada', 5, 1),
  ('people-6-full.jpg', 'people-6-regular.jpg', 'Montreal', 'Canada', 6, 1),
  ('people-7-full.jpg', 'people-7-regular.jpg', 'Toronto', 'Canada', 7, 1),
  ('people-8-full.jpg', 'people-8-regular.jpg', 'Vancouver', 'Canada', 8, 1),
  ('people-9-full.jpg', 'people-9-regular.jpg', 'Calgary', 'Canada', 9, 1),
  ('nature-1-full.jpg', 'nature-1-regular.jpg', 'Toronto', 'Canada', 1, 2),
  ('nature-2-full.jpg', 'nature-2-regular.jpg', 'Vancouver', 'Canada', 2, 2),
  ('nature-3-full.jpg', 'nature-3-regular.jpg', 'Calgary', 'Canada', 3, 2),
  ('nature-4-full.jpg', 'nature-4-regular.jpg', 'Victoria', 'Canada', 4, 2),
  ('nature-5-full.jpg', 'nature-5-regular.jpg', 'Ottawa', 'Canada', 5, 2),
  ('nature-6-full.jpg', 'nature-6-regular.jpg', 'Montreal', 'Canada', 6, 2),
  ('nature-7-full.jpg', 'nature-7-regular.jpg', 'Toronto', 'Canada', 7, 2),
  ('nature-8-full.jpg', 'nature-8-regular.jpg', 'Vancouver', 'Canada', 8, 2),
  ('nature-9-full.jpg', 'nature-9-regular.jpg', 'Calgary', 'Canada', 9, 2),
  ('travel-1-full.jpg', 'travel-1-regular.jpg', 'Toronto', 'Canada', 1, 3),
  ('travel-2-full.jpg', 'travel-2-regular.jpg', 'Vancouver', 'Canada', 2, 3),
  ('travel-3-full.jpg', 'travel-3-regular.jpg', 'Calgary', 'Canada', 3, 3),
  ('travel-4-full.jpg', 'travel-4-regular.jpg', 'Victoria', 'Canada', 4, 3),
  ('travel-5-full.jpg', 'travel-5-regular.jpg', 'Ottawa', 'Canada', 5, 3),
  ('travel-6-full.jpg', 'travel-6-regular.jpg', 'Montreal', 'Canada', 6, 3),
  ('travel-7-full.jpg', 'travel-7-regular.jpg', 'Toronto', 'Canada', 7, 3),
  ('travel-8-full.jpg', 'travel-8-regular.jpg', 'Vancouver', 'Canada', 8, 3),
  ('animals-1-full.jpg', 'animals-1-regular.jpg', 'Toronto', 'Canada', 1, 4),
  ('animals-2-full.jpg', 'animals-2-regular.jpg', 'Vancouver', 'Canada', 2, 4),
  ('animals-3-full.jpg', 'animals-3-regular.jpg', 'Calgary', 'Canada', 3, 4),
  ('animals-4-full.jpg', 'animals-4-regular.jpg', 'Victoria', 'Canada', 4, 4),
  ('animals-5-full.jpg', 'animals-5-regular.jpg', 'Ottawa', 'Canada', 5, 4),
  ('animals-6-full.jpg', 'animals-6-regular.jpg', 'Montreal', 'Canada', 6, 4),
  ('animals-7-full.jpg', 'animals-7-regular.jpg', 'Toronto', 'Canada', 7, 4),
  ('animals-8-full.jpg', 'animals-8-regular.jpg', 'Vancouver', 'Canada', 8, 4),
  ('animals-9-full.jpg', 'animals-9-regular.jpg', 'Calgary', 'Canada', 9, 4),
  ('fashion-1-full.jpg', 'fashion-1-regular.jpg', 'Toronto', 'Canada', 1, 5),
  ('fashion-2-full.jpg', 'fashion-2-regular.jpg', 'Vancouver', 'Canada', 2, 5),
  ('fashion-3-full.jpg', 'fashion-3-regular.jpg', 'Calgary', 'Canada', 3, 5),
  ('fashion-4-full.jpg', 'fashion-4-regular.jpg', 'Victoria', 'Canada', 4, 5),
  ('fashion-5-full.jpg', 'fashion-5-regular.jpg', 'Ottawa', 'Canada', 5, 5),
  ('fashion-6-full.jpg', 'fashion-6-regular.jpg', 'Montreal', 'Canada', 6, 5),
  ('fashion-7-full.jpg', 'fashion-7-regular.jpg', 'Toronto', 'Canada', 7, 5),
  ('fashion-8-full.jpg', 'fashion-8-regular.jpg', 'Vancouver', 'Canada', 8, 5),
  ('fashion-9-full.jpg', 'fashion-9-regular.jpg', 'Calgary', 'Canada', 9, 5);